#:schema node_modules/wrangler/config-schema.json
name = "sublink-work"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d9f021b7537b4c5d90a63c6784370814" }
]

[assets]
directory = "./public"
